### ISSUE TITLE
TypeError: synth() takes at least 25 positional arguments (23 given)

### ISSUE THREAD

**Issue by Hypnus1803** [aasensio/hazel#11]
Estoy intentando correr el código weakf.py  y me retorna el error TypeError: synth() takes at least 25 positional arguments (23 given). Los dos argumentos que faltan son noramlization y deltaCollision.

`Traceback (most recent call last):
  File "weakf.py", line 43, in <module>
    dopplerVelocityInput, dopplerVelocity2Input, ffInput, betaInput, beta2Input, nbarInput, omegaInput)
  File "pyhazel.pyx", line 13, in pyhazel.synth (pyhazel.c:1785)
    def synth(int synModeInput, int nSlabsInput, ar[double,ndim=1] B1Input, ar[double,ndim=1] B2Input, double hInput, 
TypeError: synth() takes at least 25 positional arguments (23 given)`

**Comment by aasensio** [comment]
This file was not updated when I modified the Python wrapper. I will upload a new version today with this issue fixed.
